# permissions for end users to edit scaledobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: scaledobject-editor-role
rules:
- apiGroups:
  - scaler.nishantsingh.sh
  resources:
  - scaledobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaler.nishantsingh.sh
  resources:
  - scaledobjects/status
  verbs:
  - get
